#!/bin/bash
#PBS -P q97
#PBS -l storage=scratch/q97
#PBS -q normal
#PBS -l walltime=05:00:00
#PBS -l mem=8GB
#PBS -l jobfs=20MB
#PBS -l ncpus=4
#PBS -l software=underworld
#PBS -l wd
#PBS -N subduction2D

source /scratch/q97/codes/UWGeodynamics_2.9.5.sh

MODELNAME="Model"
OUTPUTPATH=`pwd`
SCRIPT="geo_moresi_2014_subduction.py"

# make blas serial
export OPENBLAS_NUM_THREADS=1

mpiexec python ./$SCRIPT
